services:
  postgresdb:
    image: postgres:15-alpine
    container_name: postgres_server
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_secure_password
      POSTGRES_DB: my_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d my_database" ]
      interval: 5s
      timeout: 5s
      retries:
        5

  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://db_user:db_secure_password@postgresdb:5432/my_database
      - DATABASE_RECREATE=true
      - UVICORN_RELOAD=true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir src --reload
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      # Updated to map your local 'src' directory into the container
      - ./src:/app/src

volumes:
  postgres_data: